create table public.teams (
  source_team_id bigint generated by default as identity not null,
  season text null,
  category text null,
  team_name text null,
  rank integer null,
  photo_path text null,
  gender text null,
  membership_fee numeric null,
  age_category text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint teams_pkey primary key (source_team_id),
  constraint teams_gender_check check (
    (
      (
        gender = any (array['M'::text, 'V'::text, 'G'::text])
      )
      or (gender is null)
      or (gender = ''::text)
    )
  )
) TABLESPACE pg_default;

create index IF not exists teams_team_name_idx on public.teams using btree (team_name) TABLESPACE pg_default;

create index IF not exists teams_season_idx on public.teams using btree (season) TABLESPACE pg_default;

create index IF not exists teams_category_idx on public.teams using btree (category) TABLESPACE pg_default;

create unique INDEX IF not exists teams_source_team_id_idx on public.teams using btree (source_team_id) TABLESPACE pg_default
where
  (source_team_id is not null);