do $$
declare
  next_team_player_id bigint;
begin
  begin
    alter table public.team_players
      alter column source_team_player_id add generated by default as identity;
  exception
    when duplicate_object then
      null;
  end;

  select coalesce(max(source_team_player_id), 0) + 1
  into next_team_player_id
  from public.team_players;

  perform setval(
    pg_get_serial_sequence('public.team_players', 'source_team_player_id'),
    next_team_player_id,
    false
  );
end $$;