do $$
declare
  next_team_id bigint;
begin
  begin
    alter table public.teams
      alter column source_team_id add generated by default as identity;
  exception
    when duplicate_object then
      null;
  end;

  select coalesce(max(source_team_id), 0) + 1
  into next_team_id
  from public.teams;

  perform setval(
    pg_get_serial_sequence('public.teams', 'source_team_id'),
    next_team_id,
    false
  );
end $$;